name: Rust Audit

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses:  actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      